export const PLAY_DESTINATIONS = Object.freeze([
  {
    id: 'breath-balloon',
    type: 'arcade',
    title: 'Breath Balloon',
    eyebrow: 'Voice Arcade',
    description: 'Guide a bright balloon with a calm, steady voice or breath.',
    path: '/play/arcade/breath-balloon',
    capability: 'microphone',
    accent: 'violet',
    icon: 'balloon',
  },
  {
    id: 'river-rescue',
    type: 'quest',
    title: 'River Rescue',
    eyebrow: 'Voice Quest',
    description: 'Help a little elephant cross the river using choices and sounds.',
    path: '/play/quest/river-rescue',
    capability: 'microphone',
    accent: 'cyan',
    icon: 'map',
  },
  {
    id: 'mouth-mirror',
    type: 'mouth_mirror',
    title: 'Mouth Mirror',
    eyebrow: 'Look & Copy',
    description: 'Copy friendly mouth shapes with an optional private camera mirror.',
    path: '/play/mouth-mirror',
    capability: 'camera',
    accent: 'rose',
    icon: 'smile',
  },
  {
    id: 'pippin',
    type: 'pippin',
    title: 'Play with Pippin',
    eyebrow: 'Practice Friend',
    description: 'Talk, tap, and practise safe words with a cheerful puppy friend.',
    path: '/play/pippin',
    capability: 'microphone',
    accent: 'amber',
    icon: 'paw',
  },
  {
    id: 'talk-together',
    type: 'talk_together',
    title: 'Talk Together',
    eyebrow: 'Caregiver Mission',
    description: 'Take short, playful communication turns with a trusted grown-up.',
    path: '/play/together',
    capability: 'none',
    accent: 'green',
    icon: 'users',
  },
  {
    id: 'settings',
    type: 'settings',
    title: 'Comfort Settings',
    eyebrow: 'Grown-up Controls',
    description: 'Choose motion, sound, pace, contrast, camera, and celebration levels.',
    path: '/play/settings',
    capability: 'none',
    accent: 'slate',
    icon: 'settings',
  },
])
