#import "GeneratedPluginRegistrant.h"

@implementation GeneratedPluginRegistrant

+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry {
  // Auto-generated by flutter pub get — do not edit manually.
  // Plugin registration happens here at runtime.
}

@end
